public without sharing class AsyncActionFlowProcessor implements AsyncActions.Processor {
	@TestVisible
	private static String actionParameter = 'asyncAction';
	private static String settingParameter = 'settings';

	private Invocable.Action flow;

	public AsyncActionFlowProcessor(AsyncActionProcessor__mdt settings) {
		// TODO!
	}

	public void process(AsyncActionProcessor__mdt settings, List<AsyncAction__c> actions) {
		// TODO!
	}
}
