@IsTest 
private class AsyncActionHandlerTest {
    @IsTest 
    static void shouldLaunchJobsIfTriggerEnabled() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldNotLaunchJobsIfTriggerDisabled() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldScheduleIfEnabledAndNoneExist() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldRescheduleIfEnabledAndJobOutsideRange() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldAbortIfDisabledAndJobExists() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldDoNothingIfEnabledAndJobInRange() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldDoNothingIfDisabledAndNoneExist() {
        Assert.fail('You still need to build this test');
    }
}